### ISSUE TITLE
How to settle the TradePayment in the same Tx when user buy the NFT

### ISSUE THREAD

**Issue by rm1138** [Origin-Byte/nft-protocol#295]
I'm trying to simplify the user flow when buy/sell NFTs, and minimize the number of transaction users need to sign. 
But I don't know how to get the TradePayment ID without executed and parsed the resut of the buy NFT transaction. This force me to create another transaction to settle the TradePayment. 

I notice the "Programmable Transaction" is coming, but it also cannot access new object creation. 
https://github.com/MystenLabs/sui/issues/7790#issuecomment-1457475940

**Comment by bausano** [comment]
At the moment one would have to use a second transaction (e.g. in a cranking service or on behalf of a user.)

However, with programmable transactions, we aim to add support for exporting `TradePayment` such that royalty collection can be done with programmable transactions.

Note that in some cases in the orderbook, two transactions are always minimum. This happens when you want to buy an NFT for a floor price. You cannot know up front which NFT you are buying.

**Comment by samlaf** [comment]
> However, with programmable transactions, we aim to add support for exporting `TradePayment` such that royalty collection can be done with programmable transactions.

Are you referring to this comment [here](https://github.com/MystenLabs/sui/issues/7790#issuecomment-1457475940)?
"You will only be able to use objects generated if they are passed out as a return value to the programmable transaction runtime. There is no way to access the objects created or anything.
However! Keep in mind you can call non-entry public functions, which might help in getting to those return values."

> Note that in some cases in the orderbook, two transactions are always minimum. This happens when you want to buy an NFT for a floor price. You cannot know up front which NFT you are buying.

Can you expand on this? Don't understand why this doesn't work like the first example above.

**Comment by bausano** [comment]
We have revisited royalty enforcement in light of programmable txs.

> Can you expand on this? Don't understand why this doesn't work like the first example above.

When you trade on an orderbook, you have an option to submit orders like: buy at market price, sell at market price. However, in a fast pace orderbook, you don't know who is the buyer, or where does the NFT being sold live at.
That's because you can observe orderbook but its state changes rapidly.
But you need to provide information about the NFT to buy it.
That's why we reserve the NFT for the buyer and create an intermediate object.

**Comment by bausano** [comment]
We're now using `TransferRequest` for royalty enforcement which is a hot potato.
