### ISSUE TITLE
Error encountered while interacting with the testnet

### ISSUE THREAD

**Issue by hemanthbhushan** [Origin-Byte/nft-protocol#521]
I encountered an error while interacting with the testnet. Below is the error message I received:

```
Failed to build Move modules: Failed to resolve dependencies for package 'test_collection'

Caused by:
    When resolving dependencies for package NftProtocol, conflicting versions of package Permissions found:
    At Allowlist -> Permissions
        Permissions = { git = "https://github.com/Origin-Byte/nft-protocol.git", rev = "testnet", subdir = "contracts/permissions" }
    At Authlist -> Permissions
        Permissions = { local = "../permissions" }.
```

**Steps to Reproduce:**
1. Attempt to interact with the testnet.
2. Observe the error message mentioned above.

**Expected Behavior:**
I expected to interact with the testnet without encountering any errors.

**Additional Context:**
- This error occurs when attempting to build Move modules.
- It seems there are conflicting versions of the package 'Permissions' within the NftProtocol package.
- Here is the relevant portion of the `Move.toml` file:

```toml
[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "08119f95e9ccdc926eae3fff8c95e50678f56aed"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/nft_protocol/"
rev = "testnet"
```

**Possible Solution:**
It seems that there might be conflicting versions of the 'Permissions' package. Investigating and resolving this conflict could potentially resolve the issue.

**Any assistance in resolving this issue would be greatly appreciated. Thank you!**

**Comment by kaizu-xyz** [comment]
Hey there, thanks for pointing this out. Even though the packages were published correctly the `Move.lock` files in the `testnet` branch were outdated. The `Move.lock` are now updated, therefore you should be able to build your package now.

For reference:

```
[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet-v1.19.1"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/nft_protocol/"
rev = "v1.7.0-test-sui-v1.19.1"
```

alternatively you could use:
```
[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet-v1.19.1"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/nft_protocol/"
rev = "testnet"
```


However in future releases we plan on:
- Have our testnet and mainnet branch always point to sui mainnet and testnet (to make sure dependencies don't break in each release)
- Have our testnet tags pointing always to the associated testnet tag (instead of mainnet as illustrated above)

We will make sure to have this well documented by next release!
